import {ChecklistItemSnapshotIn} from './ChecklistItem'
import {ChecklistStoreSnapshot} from './ChecklistStore'

const preset: {[id: string]: ChecklistItemSnapshotIn} = {
  '1': {
    id: '1',
    type: 'accomodation',
    category: 'reservation',
    title: '숙소 예약',
    iconId: '🛌',
    note: '',
    isFlaggedToDelete: true,
  },
  '2': {
    id: '2',
    type: 'passport',
    category: 'foreign',
    title: '여권',
    iconId: '여권',
    note: '미리미리 할 것',
    isFlaggedToDelete: true,
  },
  '3': {
    id: '3',
    type: 'currency',
    category: 'foreign',
    title: '환전',
    iconId: '💱',
    note: '미리미리 할 것',
    isFlaggedToDelete: true,
  },
  '4': {
    id: '4',
    type: 'roaming',
    category: 'foreign',
    title: '로밍',
    iconId: '📶',
    note: '미리미리 할 것',
    isFlaggedToDelete: true,
  },
  '5': {
    id: '5',
    type: 'visit-japan',
    category: 'foreign',
    title: 'Visit Japan',
    iconId: '📝',
    note: '미리미리 할 것',
    isFlaggedToDelete: true,
  },
  '7': {
    id: '7',
    type: 'military-approvement',
    category: 'foreign',
    title: '국외여행허가',
    iconId: '🛌',
    note: '',
    isFlaggedToDelete: true,
  },
  '8': {
    id: '8',
    type: 'goods',
    category: 'goods',
    title: '세면도구',
    iconId: '🧴',
    note: '',
    isFlaggedToDelete: true,
  },
  '9': {
    id: '9',
    type: 'goods',
    category: 'goods',
    title: '어댑터',
    iconId: '🔌',
    note: '',
    isFlaggedToDelete: true,
  },
  '10': {
    id: '10',
    type: 'goods',
    category: 'goods',
    title: '선글라스',
    iconId: '🕶',
    note: '',
    isFlaggedToDelete: true,
  },
  '11': {
    id: '11',
    type: 'goods',
    category: 'goods',
    title: '캐리어',
    iconId: '🧳',
    note: '',
    isFlaggedToDelete: true,
  },
  '12': {
    id: '12',
    type: 'goods',
    category: 'goods',
    title: '우산',
    iconId: '☂️',
    note: '',
    isFlaggedToDelete: true,
  },
}

export const defaultChecklist = {
  checklistItemMap: preset,
  checklistItems: {
    reservation: [],
    foreign: [],
    goods: [],
  } as {[cateogry: string]: string[]},
  preset: Object.keys(preset).map(id => ({
    isFlaggedToAdd: true,
    item: id,
  })),
} as ChecklistStoreSnapshot
